all: crack_attack attacker_server

crack_attack: crack_attack.py
	mv crack_attack.py crack_attack
	chmod +x crack_attack

attacker_server: attacker_server.py
	mv attacker_server.py attacker_server
	chmod +x attacker_server